version: '3.4'

services:
  dotnetconsumerapp:
    image: ${DOCKER_REGISTRY-}dotnetconsumerapp
    build:
      context: .
      dockerfile: DotNetConsumerApp/Dockerfile
    networks:
     - standalone

  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
     - standalone

networks:
  standalone:
      driver: bridge
