services:
  myapp.hostapp:
    image: ${DOCKER_REGISTRY-}myapphostapp
    build:
      context: .
      dockerfile: MyApp.HostApp/Dockerfile
    depends_on:
      rabbitmq: 
        condition: service_healthy
    networks:
      - myapp

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - myapp


volumes:
  rabbitmq-data:

networks:
  myapp:
    driver: bridge    

